FROM node:18-alpine

WORKDIR /workspace

COPY pnpm-lock.yaml ./
COPY package.json ./
COPY pnpm-workspace.yaml ./

RUN npm install -g pnpm
COPY . .
RUN pnpm install --filter './apps/client...'

WORKDIR /workspace/apps/client
RUN pnpm install

EXPOSE 3000

CMD ["pnpm", "run", "dev", "--", "--host"]