version: '3.9'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - '3000:3000'
    volumes:
      - .:/workspace
      - /workspace/node_modules
    depends_on:
      - api
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: "no"
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - '5001:5001'
    volumes:
      - .:/workspace
      - /workspace/node_modules
    # depends_on:
    #   - db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: "no"
    # depends_on:
    #   - db
  # db:
  #   image: postgres:latest
  #   environment:
  #     POSTGRES_USER: user
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: mydatabase
  #   ports:
  #     - '5432:5432'
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:
